"""migration

Revision ID: 09f98d7ac23c
Revises:
Create Date: 2025-10-04 20:09:33.658080

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "09f98d7ac23c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "incoming_webhooks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "organizations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "runtimes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("hash", sa.String(length=64), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hash"),
        sa.UniqueConstraint("name", "version", name="uq_runtime_name_version"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workos_user_id", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workos_user_id"),
    )
    op.create_table(
        "namespaces",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("user_owner_id", sa.UUID(), nullable=True),
        sa.Column("organization_owner_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "(user_owner_id IS NOT NULL)::int + (organization_owner_id IS NOT NULL)::int = 1",
            name="chk_namespace_single_owner",
        ),
        sa.ForeignKeyConstraint(
            ["organization_owner_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        "idx_namespaces_organization_owner",
        "namespaces",
        ["organization_owner_id"],
        unique=False,
    )
    op.create_index(
        "idx_namespaces_user_owner", "namespaces", ["user_owner_id"], unique=False
    )
    op.create_table(
        "organization_members",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("OWNER", "ADMIN", "MEMBER", name="organizationrole"),
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "user_id", name="uq_organization_user"),
    )
    op.create_index(
        "idx_organization_members_organization",
        "organization_members",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "idx_organization_members_user",
        "organization_members",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "namespace_members",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("namespace_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("OWNER", "ADMIN", "WRITE", "READ", name="namespacerole"),
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["namespace_id"], ["namespaces.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("namespace_id", "user_id", name="uq_namespace_user"),
    )
    op.create_index(
        "idx_namespace_members_namespace",
        "namespace_members",
        ["namespace_id"],
        unique=False,
    )
    op.create_index(
        "idx_namespace_members_user", "namespace_members", ["user_id"], unique=False
    )
    op.create_table(
        "workflows",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("namespace_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["namespace_id"], ["namespaces.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("namespace_id", "name", name="uq_namespace_workflow"),
    )
    op.create_index(
        "idx_workflows_created_by", "workflows", ["created_by_id"], unique=False
    )
    op.create_index(
        "idx_workflows_namespace", "workflows", ["namespace_id"], unique=False
    )
    op.create_index(
        "idx_workflows_updated_at", "workflows", ["updated_at"], unique=False
    )
    op.create_table(
        "incoming_webhook_listeners",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("webhook_id", sa.UUID(), nullable=False),
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column(
            "listener_type",
            sa.Enum("PUBLISHED_WORKFLOW", "LOCAL_WORKFLOW", name="webhooklistenertype"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["webhook_id"], ["incoming_webhooks.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["workflow_id"], ["workflows.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "workflow_deployments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("runtime_id", sa.UUID(), nullable=False),
        sa.Column("deployed_by_id", sa.UUID(), nullable=True),
        sa.Column(
            "deployed_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", "FAILED", name="workflowdeploymentstatus"),
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["deployed_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["runtime_id"], ["runtimes.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["workflow_id"], ["workflows.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_workflow_deployments_status",
        "workflow_deployments",
        ["status"],
        unique=False,
    )
    op.create_index(
        "idx_workflow_deployments_workflow",
        "workflow_deployments",
        ["workflow_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_workflow_deployments_workflow", table_name="workflow_deployments"
    )
    op.drop_index("idx_workflow_deployments_status", table_name="workflow_deployments")
    op.drop_table("workflow_deployments")
    op.drop_table("incoming_webhook_listeners")
    op.drop_index("idx_workflows_updated_at", table_name="workflows")
    op.drop_index("idx_workflows_namespace", table_name="workflows")
    op.drop_index("idx_workflows_created_by", table_name="workflows")
    op.drop_table("workflows")
    op.drop_index("idx_namespace_members_user", table_name="namespace_members")
    op.drop_index("idx_namespace_members_namespace", table_name="namespace_members")
    op.drop_table("namespace_members")
    op.drop_index("idx_organization_members_user", table_name="organization_members")
    op.drop_index(
        "idx_organization_members_organization", table_name="organization_members"
    )
    op.drop_table("organization_members")
    op.drop_index("idx_namespaces_user_owner", table_name="namespaces")
    op.drop_index("idx_namespaces_organization_owner", table_name="namespaces")
    op.drop_table("namespaces")
    op.drop_table("users")
    op.drop_table("runtimes")
    op.drop_table("organizations")
    op.drop_table("incoming_webhooks")
    # ### end Alembic commands ###
