"""migration

Revision ID: 03a9b723c0fa
Revises: 09f98d7ac23c
Create Date: 2025-10-05 14:56:42.491110

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "03a9b723c0fa"
down_revision = "09f98d7ac23c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "secrets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("namespace_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("provider", sa.String(length=255), nullable=False),
        sa.Column("encrypted_value", sa.Text(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["namespace_id"], ["namespaces.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("namespace_id", "name", name="uq_namespace_secret"),
    )
    op.create_index("idx_secrets_namespace", "secrets", ["namespace_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_secrets_namespace", table_name="secrets")
    op.drop_table("secrets")
    # ### end Alembic commands ###
