"""migration

Revision ID: 8674c73e271c
Revises: 03a9b723c0fa
Create Date: 2025-10-06 19:36:21.877317

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "8674c73e271c"
down_revision = "03a9b723c0fa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("incoming_webhook_listeners")
    op.add_column(
        "incoming_webhooks", sa.Column("workflow_id", sa.UUID(), nullable=False)
    )
    op.create_foreign_key(
        None,
        "incoming_webhooks",
        "workflows",
        ["workflow_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "incoming_webhooks", type_="foreignkey")
    op.drop_column("incoming_webhooks", "workflow_id")
    op.create_table(
        "incoming_webhook_listeners",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("webhook_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("workflow_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "listener_type",
            postgresql.ENUM(
                "PUBLISHED_WORKFLOW", "LOCAL_WORKFLOW", name="webhooklistenertype"
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["webhook_id"],
            ["incoming_webhooks.id"],
            name=op.f("incoming_webhook_listeners_webhook_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflows.id"],
            name=op.f("incoming_webhook_listeners_workflow_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("incoming_webhook_listeners_pkey")),
    )
    # ### end Alembic commands ###
