"""migration

Revision ID: 8bfc9dff07c8
Revises: 8674c73e271c
Create Date: 2025-10-11 16:03:49.662553

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "8bfc9dff07c8"
down_revision = "8674c73e271c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workflow_deployments",
        sa.Column("user_code", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workflow_deployments", "user_code")
    # ### end Alembic commands ###
