"""migration

Revision ID: 948186fdad21
Revises: 8bfc9dff07c8
Create Date: 2025-10-11 19:58:31.624441

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "948186fdad21"
down_revision = "8bfc9dff07c8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("idx_namespace_members_namespace"), table_name="namespace_members"
    )
    op.drop_index(op.f("idx_namespace_members_user"), table_name="namespace_members")
    op.drop_table("namespace_members")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "namespace_members",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("namespace_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "role",
            postgresql.ENUM("OWNER", "ADMIN", "WRITE", "READ", name="namespacerole"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["namespace_id"],
            ["namespaces.id"],
            name=op.f("namespace_members_namespace_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("namespace_members_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("namespace_members_pkey")),
        sa.UniqueConstraint(
            "namespace_id",
            "user_id",
            name=op.f("uq_namespace_user"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("idx_namespace_members_user"),
        "namespace_members",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_namespace_members_namespace"),
        "namespace_members",
        ["namespace_id"],
        unique=False,
    )
    # ### end Alembic commands ###
