"""migration

Revision ID: 12c4c42f1f26
Revises: 948186fdad21
Create Date: 2025-10-12 12:29:40.688245

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "12c4c42f1f26"
down_revision = "948186fdad21"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("IN_PROGRESS", "COMPLETED", "FAILED", name="runtimecreationstatus").create(
        op.get_bind()
    )
    op.add_column("runtimes", sa.Column("config_hash", sa.UUID(), nullable=False))
    op.add_column(
        "runtimes",
        sa.Column(
            "creation_status",
            postgresql.ENUM(
                "IN_PROGRESS",
                "COMPLETED",
                "FAILED",
                name="runtimecreationstatus",
                create_type=False,
            ),
            nullable=False,
        ),
    )
    op.add_column(
        "runtimes",
        sa.Column(
            "creation_logs", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.drop_constraint(op.f("runtimes_hash_key"), "runtimes", type_="unique")
    op.drop_constraint(op.f("uq_runtime_name_version"), "runtimes", type_="unique")
    op.create_unique_constraint("uq_runtime_config_hash", "runtimes", ["config_hash"])
    op.drop_column("runtimes", "name")
    op.drop_column("runtimes", "hash")
    op.drop_column("runtimes", "version")
    sa.Enum("OWNER", "ADMIN", "WRITE", "READ", name="namespacerole").drop(op.get_bind())
    sa.Enum("PUBLISHED_WORKFLOW", "LOCAL_WORKFLOW", name="webhooklistenertype").drop(
        op.get_bind()
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("PUBLISHED_WORKFLOW", "LOCAL_WORKFLOW", name="webhooklistenertype").create(
        op.get_bind()
    )
    sa.Enum("OWNER", "ADMIN", "WRITE", "READ", name="namespacerole").create(
        op.get_bind()
    )
    op.add_column(
        "runtimes",
        sa.Column(
            "version", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "runtimes",
        sa.Column("hash", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    )
    op.add_column(
        "runtimes",
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    )
    op.drop_constraint("uq_runtime_config_hash", "runtimes", type_="unique")
    op.create_unique_constraint(
        op.f("uq_runtime_name_version"),
        "runtimes",
        ["name", "version"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("runtimes_hash_key"),
        "runtimes",
        ["hash"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("runtimes", "creation_logs")
    op.drop_column("runtimes", "creation_status")
    op.drop_column("runtimes", "config_hash")
    sa.Enum("IN_PROGRESS", "COMPLETED", "FAILED", name="runtimecreationstatus").drop(
        op.get_bind()
    )
    # ### end Alembic commands ###
