"""migration

Revision ID: 587d99894f72
Revises: 12c4c42f1f26
Create Date: 2025-10-20 22:57:14.264711

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "587d99894f72"
down_revision = "12c4c42f1f26"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "providers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("namespace_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("alias", sa.Text(), nullable=False),
        sa.Column("encrypted_config", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["namespace_id"], ["namespaces.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("providers")
    # ### end Alembic commands ###
