"""migration

Revision ID: d1f38cda3e0c
Revises: a8b9c1d2e3f4
Create Date: 2025-10-27 18:51:03.542844

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d1f38cda3e0c"
down_revision = "a8b9c1d2e3f4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "triggers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("provider_id", sa.UUID(), nullable=False),
        sa.Column("trigger_type", sa.Text(), nullable=False),
        sa.Column("input", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("state", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(["provider_id"], ["providers.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["workflow_id"], ["workflows.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "recurring_tasks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("trigger_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["trigger_id"], ["triggers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "incoming_webhooks", sa.Column("trigger_id", sa.UUID(), nullable=False)
    )
    op.drop_constraint(
        op.f("uq_incoming_webhook_path_method"), "incoming_webhooks", type_="unique"
    )
    op.drop_constraint(
        op.f("incoming_webhooks_workflow_id_fkey"),
        "incoming_webhooks",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "incoming_webhooks",
        "triggers",
        ["trigger_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("incoming_webhooks", "workflow_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "incoming_webhooks",
        sa.Column("workflow_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "incoming_webhooks", type_="foreignkey")
    op.create_foreign_key(
        op.f("incoming_webhooks_workflow_id_fkey"),
        "incoming_webhooks",
        "workflows",
        ["workflow_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_unique_constraint(
        op.f("uq_incoming_webhook_path_method"),
        "incoming_webhooks",
        ["path", "method"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("incoming_webhooks", "trigger_id")
    op.drop_table("recurring_tasks")
    op.drop_table("triggers")
    # ### end Alembic commands ###
