"""migration

Revision ID: c5d72cc842e7
Revises: d1f38cda3e0c
Create Date: 2025-10-29 23:21:57.988888

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c5d72cc842e7"
down_revision = "d1f38cda3e0c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organizations",
        sa.Column("workos_organization_id", sa.String(length=255), nullable=True),
    )
    op.create_unique_constraint(None, "organizations", ["workos_organization_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "organizations", type_="unique")
    op.drop_column("organizations", "workos_organization_id")
    # ### end Alembic commands ###
