"""migration

Revision ID: 9f660ec41b18
Revises: c5d72cc842e7
Create Date: 2025-10-30 20:44:27.047187

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9f660ec41b18"
down_revision = "c5d72cc842e7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "organizations",
        "workos_organization_id",
        existing_type=sa.VARCHAR(length=255),
        nullable=True,
    )
    op.add_column("users", sa.Column("email", sa.String(length=255), nullable=True))
    op.add_column(
        "users", sa.Column("first_name", sa.String(length=255), nullable=True)
    )
    op.add_column("users", sa.Column("last_name", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    op.drop_column("users", "email")
    op.alter_column(
        "organizations",
        "workos_organization_id",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
    )
    # ### end Alembic commands ###
