"""migration

Revision ID: 1f9fe24442c7
Revises: 9f660ec41b18
Create Date: 2025-10-30 22:12:26.890217

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1f9fe24442c7"
down_revision = "9f660ec41b18"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("namespaces_name_key"), "namespaces", type_="unique")
    op.drop_column("namespaces", "name")
    op.drop_column("namespaces", "display_name")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "namespaces",
        sa.Column(
            "display_name", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "namespaces",
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    )
    op.create_unique_constraint(
        op.f("namespaces_name_key"),
        "namespaces",
        ["name"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
