"""migration

Revision ID: ae804c8e4248
Revises: 2a3b4c5d6e7f
Create Date: 2025-11-07 18:39:23.786149

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ae804c8e4248"
down_revision = "2a3b4c5d6e7f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("HUMAN", "SERVICE_ACCOUNT", name="usertype").create(op.get_bind())
    op.create_table(
        "api_keys",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("prefix", sa.Text(), nullable=False),
        sa.Column("hashed_key", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "prefix", name="uq_user_api_key_prefix"),
    )
    op.add_column(
        "users",
        sa.Column(
            "user_type",
            postgresql.ENUM(
                "HUMAN", "SERVICE_ACCOUNT", name="usertype", create_type=False
            ),
            nullable=False,
        ),
    )
    op.alter_column(
        "users", "workos_user_id", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "workos_user_id", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.drop_column("users", "user_type")
    op.drop_table("api_keys")
    sa.Enum("HUMAN", "SERVICE_ACCOUNT", name="usertype").drop(op.get_bind())
    # ### end Alembic commands ###
