"""migration

Revision ID: eaa62e1b9f5e
Revises: 3b4c5d6e7f8g
Create Date: 2025-11-08 10:44:44.081787

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "eaa62e1b9f5e"
down_revision = "3b4c5d6e7f8g"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("api_keys", "user_id", existing_type=sa.UUID(), nullable=False)
    op.drop_constraint(op.f("api_keys_user_id_fkey"), "api_keys", type_="foreignkey")
    op.create_foreign_key(
        None, "api_keys", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "api_keys", type_="foreignkey")
    op.create_foreign_key(
        op.f("api_keys_user_id_fkey"),
        "api_keys",
        "users",
        ["user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.alter_column("api_keys", "user_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###
