"""migration

Revision ID: 015c90d8be6e
Revises: cae9b9e47fac
Create Date: 2025-11-09 12:07:21.291859

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "015c90d8be6e"
down_revision = "cae9b9e47fac"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(
        "RECEIVED",
        "STARTED",
        "COMPLETED",
        "FAILED",
        "TIMEOUT",
        "NO_DEPLOYMENT",
        name="executionstatus",
    ).create(op.get_bind())
    op.create_table(
        "execution_history",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("trigger_id", sa.UUID(), nullable=True),
        sa.Column("deployment_id", sa.UUID(), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "RECEIVED",
                "STARTED",
                "COMPLETED",
                "FAILED",
                "TIMEOUT",
                "NO_DEPLOYMENT",
                name="executionstatus",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("error_stack", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["deployment_id"], ["workflow_deployments.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["trigger_id"], ["triggers.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["workflow_id"], ["workflows.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_execution_history_deployment",
        "execution_history",
        ["deployment_id"],
        unique=False,
    )
    op.create_index(
        "idx_execution_history_received_at",
        "execution_history",
        ["received_at"],
        unique=False,
    )
    op.create_index(
        "idx_execution_history_status", "execution_history", ["status"], unique=False
    )
    op.create_index(
        "idx_execution_history_trigger",
        "execution_history",
        ["trigger_id"],
        unique=False,
    )
    op.create_index(
        "idx_execution_history_workflow",
        "execution_history",
        ["workflow_id"],
        unique=False,
    )
    op.create_index(
        "idx_execution_history_workflow_received",
        "execution_history",
        ["workflow_id", "received_at"],
        unique=False,
    )
    op.create_index(
        "idx_execution_history_workflow_status",
        "execution_history",
        ["workflow_id", "status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_execution_history_workflow_status", table_name="execution_history"
    )
    op.drop_index(
        "idx_execution_history_workflow_received", table_name="execution_history"
    )
    op.drop_index("idx_execution_history_workflow", table_name="execution_history")
    op.drop_index("idx_execution_history_trigger", table_name="execution_history")
    op.drop_index("idx_execution_history_status", table_name="execution_history")
    op.drop_index("idx_execution_history_received_at", table_name="execution_history")
    op.drop_index("idx_execution_history_deployment", table_name="execution_history")
    op.drop_table("execution_history")
    sa.Enum(
        "RECEIVED",
        "STARTED",
        "COMPLETED",
        "FAILED",
        "TIMEOUT",
        "NO_DEPLOYMENT",
        name="executionstatus",
    ).drop(op.get_bind())
    # ### end Alembic commands ###
