"""migration

Revision ID: ac3d8ff8c23f
Revises: 015c90d8be6e
Create Date: 2025-11-10 08:42:54.909047

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ac3d8ff8c23f"
down_revision = "015c90d8be6e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("kv_tables", sa.Column("provider_id", sa.UUID(), nullable=False))
    op.drop_index(op.f("idx_kv_tables_namespace"), table_name="kv_tables")
    op.drop_constraint(op.f("uq_namespace_table_name"), "kv_tables", type_="unique")
    op.create_index(
        "idx_kv_tables_provider", "kv_tables", ["provider_id"], unique=False
    )
    op.create_unique_constraint(
        "uq_provider_table_name", "kv_tables", ["provider_id", "name"]
    )
    op.drop_constraint(
        op.f("kv_tables_namespace_id_fkey"), "kv_tables", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "kv_tables", "providers", ["provider_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("kv_tables", "namespace_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "kv_tables",
        sa.Column("namespace_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "kv_tables", type_="foreignkey")
    op.create_foreign_key(
        op.f("kv_tables_namespace_id_fkey"),
        "kv_tables",
        "namespaces",
        ["namespace_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("uq_provider_table_name", "kv_tables", type_="unique")
    op.drop_index("idx_kv_tables_provider", table_name="kv_tables")
    op.create_unique_constraint(
        op.f("uq_namespace_table_name"),
        "kv_tables",
        ["namespace_id", "name"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("idx_kv_tables_namespace"), "kv_tables", ["namespace_id"], unique=False
    )
    op.drop_column("kv_tables", "provider_id")
    # ### end Alembic commands ###
