"""add subscriptions and billing

Revision ID: 2cd7836b4d4d
Revises: ac3d8ff8c23f
Create Date: 2025-11-15 20:49:51.910456

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2cd7836b4d4d"
down_revision = "ac3d8ff8c23f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(
        "ACTIVE",
        "TRIALING",
        "PAST_DUE",
        "CANCELED",
        "INCOMPLETE",
        name="subscriptionstatus",
    ).create(op.get_bind())
    sa.Enum("FREE", "HOBBY", name="subscriptiontier").create(op.get_bind())
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("stripe_customer_id", sa.String(length=255), nullable=True),
        sa.Column("stripe_subscription_id", sa.String(length=255), nullable=True),
        sa.Column(
            "tier",
            postgresql.ENUM(
                "FREE", "HOBBY", name="subscriptiontier", create_type=False
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "ACTIVE",
                "TRIALING",
                "PAST_DUE",
                "CANCELED",
                "INCOMPLETE",
                name="subscriptionstatus",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("trial_ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("grace_period_ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_at_period_end", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("stripe_customer_id"),
        sa.UniqueConstraint("stripe_subscription_id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(
        "idx_subscriptions_user", "subscriptions", ["user_id"], unique=False
    )
    op.create_table(
        "billing_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("subscription_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=255), nullable=False),
        sa.Column("stripe_event_id", sa.String(length=255), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"], ["subscriptions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("stripe_event_id"),
    )
    op.create_index(
        "idx_billing_events_created_at", "billing_events", ["created_at"], unique=False
    )
    op.create_index(
        "idx_billing_events_event_type", "billing_events", ["event_type"], unique=False
    )
    op.create_index(
        "idx_billing_events_subscription",
        "billing_events",
        ["subscription_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_billing_events_subscription", table_name="billing_events")
    op.drop_index("idx_billing_events_event_type", table_name="billing_events")
    op.drop_index("idx_billing_events_created_at", table_name="billing_events")
    op.drop_table("billing_events")
    op.drop_index("idx_subscriptions_user", table_name="subscriptions")
    op.drop_table("subscriptions")
    sa.Enum("FREE", "HOBBY", name="subscriptiontier").drop(op.get_bind())
    sa.Enum(
        "ACTIVE",
        "TRIALING",
        "PAST_DUE",
        "CANCELED",
        "INCOMPLETE",
        name="subscriptionstatus",
    ).drop(op.get_bind())
    # ### end Alembic commands ###
