"""Add is_admin field to User model

Revision ID: 32482a0d5dbc
Revises: 2cd7836b4d4d
Create Date: 2025-11-16 14:53:21.188968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32482a0d5dbc'
down_revision = '2cd7836b4d4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###