"""migration

Revision ID: fa47b44b0db3
Revises: 32482a0d5dbc
Create Date: 2025-11-21 21:58:10.438754

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "fa47b44b0db3"
down_revision = "32482a0d5dbc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("execution_history", sa.Column("logs", sa.Text(), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("execution_history", "logs")
    # ### end Alembic commands ###
