"""migration

Revision ID: 4ceee1f0c843
Revises: fa47b44b0db3
Create Date: 2025-11-23 21:50:03.128589

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "4ceee1f0c843"
down_revision = "fa47b44b0db3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workflow_deployments",
        sa.Column(
            "provider_definitions",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    op.add_column(
        "workflow_deployments",
        sa.Column(
            "trigger_definitions",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workflow_deployments", "trigger_definitions")
    op.drop_column("workflow_deployments", "provider_definitions")
    # ### end Alembic commands ###
