"""migration

Revision ID: e04c404a0d65
Revises: 4ceee1f0c843
Create Date: 2025-11-30 18:18:29.513900

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e04c404a0d65"
down_revision = "4ceee1f0c843"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workflows", sa.Column("active", sa.Boolean(), nullable=True))
    op.create_index("idx_workflows_active", "workflows", ["active"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_workflows_active", table_name="workflows")
    op.drop_column("workflows", "active")
    # ### end Alembic commands ###
