"""migration

Revision ID: 495221d2854c
Revises: e04c404a0d65
Create Date: 2025-11-30 22:51:23.633103

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "495221d2854c"
down_revision = "e04c404a0d65"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("PENDING", "APPROVED", "DENIED", "EXPIRED", name="devicecodestatus").create(
        op.get_bind()
    )
    op.create_table(
        "device_codes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("device_code", sa.String(length=64), nullable=False),
        sa.Column("user_code", sa.String(length=16), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "PENDING",
                "APPROVED",
                "DENIED",
                "EXPIRED",
                name="devicecodestatus",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_code"),
        sa.UniqueConstraint("user_code"),
    )
    op.create_index(
        "idx_device_codes_device_code", "device_codes", ["device_code"], unique=False
    )
    op.create_index(
        "idx_device_codes_expires_at", "device_codes", ["expires_at"], unique=False
    )
    op.create_index("idx_device_codes_status", "device_codes", ["status"], unique=False)
    op.create_index(
        "idx_device_codes_user_code", "device_codes", ["user_code"], unique=False
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("device_name", sa.String(length=255), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_used_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(
        "idx_refresh_tokens_revoked_at", "refresh_tokens", ["revoked_at"], unique=False
    )
    op.create_index(
        "idx_refresh_tokens_token_hash", "refresh_tokens", ["token_hash"], unique=False
    )
    op.create_index(
        "idx_refresh_tokens_user_id", "refresh_tokens", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_refresh_tokens_user_id", table_name="refresh_tokens")
    op.drop_index("idx_refresh_tokens_token_hash", table_name="refresh_tokens")
    op.drop_index("idx_refresh_tokens_revoked_at", table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index("idx_device_codes_user_code", table_name="device_codes")
    op.drop_index("idx_device_codes_status", table_name="device_codes")
    op.drop_index("idx_device_codes_expires_at", table_name="device_codes")
    op.drop_index("idx_device_codes_device_code", table_name="device_codes")
    op.drop_table("device_codes")
    sa.Enum("PENDING", "APPROVED", "DENIED", "EXPIRED", name="devicecodestatus").drop(
        op.get_bind()
    )
    # ### end Alembic commands ###
