"""add_execution_logs_table

Revision ID: 20024c653804
Revises: 495221d2854c
Create Date: 2025-12-03 22:31:55.176951

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "20024c653804"
down_revision = "495221d2854c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("DEBUG", "INFO", "WARN", "ERROR", "LOG", name="loglevel").create(
        op.get_bind()
    )
    op.create_table(
        "execution_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("execution_history_id", sa.UUID(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "log_level",
            postgresql.ENUM(
                "DEBUG",
                "INFO",
                "WARN",
                "ERROR",
                "LOG",
                name="loglevel",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["execution_history_id"], ["execution_history.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_execution_logs_execution_id",
        "execution_logs",
        ["execution_history_id"],
        unique=False,
    )
    op.create_index(
        "idx_execution_logs_level", "execution_logs", ["log_level"], unique=False
    )
    op.create_index(
        "idx_execution_logs_timestamp", "execution_logs", ["timestamp"], unique=False
    )
    op.add_column(
        "execution_history", sa.Column("duration_ms", sa.Integer(), nullable=True)
    )
    op.drop_column("execution_history", "error_stack")
    op.drop_column("execution_history", "logs")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "execution_history",
        sa.Column("logs", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "execution_history",
        sa.Column("error_stack", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.drop_column("execution_history", "duration_ms")
    op.drop_index("idx_execution_logs_timestamp", table_name="execution_logs")
    op.drop_index("idx_execution_logs_level", table_name="execution_logs")
    op.drop_index("idx_execution_logs_execution_id", table_name="execution_logs")
    op.drop_table("execution_logs")
    sa.Enum("DEBUG", "INFO", "WARN", "ERROR", "LOG", name="loglevel").drop(
        op.get_bind()
    )
    # ### end Alembic commands ###
