"""migration

Revision ID: 222b0e177297
Revises: 20024c653804
Create Date: 2025-12-04 22:35:03.912519

"""

from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision = "222b0e177297"
down_revision = "20024c653804"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="runtimecreationstatus",
        new_values=["IN_PROGRESS", "COMPLETED", "FAILED", "REMOVED"],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="runtimes",
                column_name="creation_status",
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="runtimecreationstatus",
        new_values=["IN_PROGRESS", "COMPLETED", "FAILED"],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="runtimes",
                column_name="creation_status",
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
