"""migration

Revision ID: 8b2f4e24f222
Revises: 222b0e177297
Create Date: 2025-12-25 17:34:33.035174

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8b2f4e24f222"
down_revision = "222b0e177297"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscriptions", sa.Column("organization_id", sa.UUID(), nullable=False)
    )
    op.drop_index(op.f("idx_subscriptions_user"), table_name="subscriptions")
    op.drop_constraint(
        op.f("subscriptions_user_id_key"), "subscriptions", type_="unique"
    )
    op.create_index(
        "idx_subscriptions_organization",
        "subscriptions",
        ["organization_id"],
        unique=False,
    )
    op.create_unique_constraint(None, "subscriptions", ["organization_id"])
    op.drop_constraint(
        op.f("subscriptions_user_id_fkey"), "subscriptions", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "subscriptions",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("subscriptions", "user_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscriptions",
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "subscriptions", type_="foreignkey")
    op.create_foreign_key(
        op.f("subscriptions_user_id_fkey"),
        "subscriptions",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "subscriptions", type_="unique")
    op.drop_index("idx_subscriptions_organization", table_name="subscriptions")
    op.create_unique_constraint(
        op.f("subscriptions_user_id_key"),
        "subscriptions",
        ["user_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("idx_subscriptions_user"), "subscriptions", ["user_id"], unique=False
    )
    op.drop_column("subscriptions", "organization_id")
    # ### end Alembic commands ###
