"""migration

Revision ID: b66713463020
Revises: 8b2f4e24f222
Create Date: 2025-12-27 12:25:24.064766

"""

import sqlalchemy as sa
from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision = "b66713463020"
down_revision = "8b2f4e24f222"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("organizations_name_key"), "organizations", type_="unique")
    op.drop_column("organizations", "name")
    op.sync_enum_values(
        enum_schema="public",
        enum_name="subscriptiontier",
        new_values=["FREE", "HOBBY", "TEAM"],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="subscriptions", column_name="tier"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="subscriptiontier",
        new_values=["FREE", "HOBBY"],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="subscriptions", column_name="tier"
            )
        ],
        enum_values_to_rename=[],
    )
    op.add_column(
        "organizations",
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    )
    op.create_unique_constraint(
        op.f("organizations_name_key"),
        "organizations",
        ["name"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
