"""migration

Revision ID: 255dd988c311
Revises: 692747f18ded
Create Date: 2026-01-03 17:35:52.736862

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "255dd988c311"
down_revision = "692747f18ded"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("OWNER", "USER", name="accessrole").create(op.get_bind())
    sa.Enum("USER", "WORKFLOW", "FOLDER", name="principletype").create(op.get_bind())
    sa.Enum("WORKFLOW", "FOLDER", "PROVIDER", name="resourcetype").create(op.get_bind())
    op.create_table(
        "provider_access",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "resource_type",
            postgresql.ENUM(
                "WORKFLOW", "FOLDER", "PROVIDER", name="resourcetype", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("resource_id", sa.UUID(), nullable=False),
        sa.Column(
            "principle_type",
            postgresql.ENUM(
                "USER", "WORKFLOW", "FOLDER", name="principletype", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("principle_id", sa.UUID(), nullable=False),
        sa.Column(
            "role",
            postgresql.ENUM("OWNER", "USER", name="accessrole", create_type=False),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "principle_type",
            "principle_id",
            "resource_type",
            "resource_id",
            name="uq_access_principal_resource",
        ),
    )
    op.create_index(
        "idx_access_principal",
        "provider_access",
        ["principle_type", "principle_id"],
        unique=False,
    )
    op.create_index(
        "idx_access_resource",
        "provider_access",
        ["resource_type", "resource_id"],
        unique=False,
    )
    op.create_table(
        "workflow_folders",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("namespace_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("parent_folder_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["namespace_id"], ["namespaces.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["parent_folder_id"], ["workflow_folders.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("workflows", sa.Column("parent_folder_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        None,
        "workflows",
        "workflow_folders",
        ["parent_folder_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "workflows", type_="foreignkey")
    op.drop_column("workflows", "parent_folder_id")
    op.drop_table("workflow_folders")
    op.drop_index("idx_access_resource", table_name="provider_access")
    op.drop_index("idx_access_principal", table_name="provider_access")
    op.drop_table("provider_access")
    sa.Enum("WORKFLOW", "FOLDER", "PROVIDER", name="resourcetype").drop(op.get_bind())
    sa.Enum("USER", "WORKFLOW", "FOLDER", name="principletype").drop(op.get_bind())
    sa.Enum("OWNER", "USER", name="accessrole").drop(op.get_bind())
    # ### end Alembic commands ###
