version: "3.8"

services:
  centrifugo:
    image: "ghcr.io/usefloww/floww-centrifugo:${IMAGE_TAG:-latest}"

    networks:
      - traefik-net

    secrets:
      - backend_centrifugo_api_key

    environment:
      - CENTRIFUGO_API_KEY_FILE=/run/secrets/backend_centrifugo_api_key
      - CENTRIFUGO_ADMIN_ENABLED=true
      - CENTRIFUGO_ADMIN_INSECURE=true
      - CENTRIFUGO_CONNECT_PROXY_ENDPOINT=http://floww-backend_app:8000/centrifugo/connect
      - CENTRIFUGO_SUBSCRIBE_PROXY_ENDPOINT=http://floww-backend_app:8000/centrifugo/subscribe
      - CENTRIFUGO_ALLOWED_ORIGINS=["https://app.usefloww.dev"]
      - CENTRIFUGO_ALLOW_ANONYMOUS=true

    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
      rollback_config:
        parallelism: 1
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.centrifugo.rule=Host(`app.usefloww.dev`) && PathPrefix(`/ws`)"
        - "traefik.http.routers.centrifugo.entrypoints=websecure"
        - "traefik.http.routers.centrifugo.tls.certresolver=myresolver"
        - "traefik.http.services.centrifugo-service.loadbalancer.server.port=8000"

    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  app:
    image: "ghcr.io/usefloww/floww-backend:${IMAGE_TAG:-latest}"

    networks:
      - traefik-net

    secrets:
      - backend_auth_client_secret
      - backend_encryption_key
      - backend_aws_access_key_id
      - backend_aws_secret_access_key
      - backend_database_password
      - backend_session_secret_key
      - backend_workflow_jwt_secret
      - backend_centrifugo_api_key
      - backend_centrifugo_jwt_secret
      - backend_sentry_dsn
      - backend_stripe_secret_key
      - backend_stripe_webhook_secret
      - backend_openrouter_api_key
      - backend_google_oauth_client_id
      - backend_google_oauth_client_secret

    environment:
      # Non-sensitive configuration
      - AUTH_CLIENT_ID=client_01K6QQP8Q721ZX1YM1PBV3EWMR
      - AUTH_ISSUER_URL=https://great-gradient-36-staging.authkit.app
      - AWS_REGION=us-east-1
      - RUNTIME_TYPE=lambda
      - DATABASE_USER=postgres
      - DATABASE_HOST=floww.cklmackcedxs.us-east-1.rds.amazonaws.com
      - DATABASE_PORT=5432
      - DATABASE_NAME=postgres
      - CENTRIFUGO_HOST=centrifugo
      - CENTRIFUGO_PORT=8000
      - CENTRIFUGO_PUBLIC_URL=https://app.usefloww.dev
      - PUBLIC_API_URL=https://app.usefloww.dev
      - SENTRY_ENVIRONMENT=production
      - REGISTRY_URL=501046919403.dkr.ecr.us-east-1.amazonaws.com
      - REGISTRY_REPOSITORY_NAME=trigger-lambda
      - IS_CLOUD=true
      - STRIPE_PUBLISHABLE_KEY=pk_live_51SToIG9QR0ekoyxExl6rbZdjKrPubJFpPMe2dCiG7BxsVrJuQ04GP5QsMWQwg1L1s1tz255LV0JQMw2izZfHyeKZ00stQnGCze
      - STRIPE_PRICE_ID_HOBBY=price_1SjjFK9QR0ekoyxEJlYJwPmb
      - STRIPE_PRICE_ID_TEAM=price_1SjjFK9QR0ekoyxEJKp9zl6q

      # Secret file paths (read by updated settings.py)
      - AUTH_CLIENT_SECRET_FILE=/run/secrets/backend_auth_client_secret
      - ENCRYPTION_KEY_FILE=/run/secrets/backend_encryption_key
      - AWS_ACCESS_KEY_ID_FILE=/run/secrets/backend_aws_access_key_id
      - AWS_SECRET_ACCESS_KEY_FILE=/run/secrets/backend_aws_secret_access_key
      - DATABASE_PASSWORD_FILE=/run/secrets/backend_database_password
      - SESSION_SECRET_KEY_FILE=/run/secrets/backend_session_secret_key
      - WORKFLOW_JWT_SECRET_FILE=/run/secrets/backend_workflow_jwt_secret
      - CENTRIFUGO_API_KEY_FILE=/run/secrets/backend_centrifugo_api_key
      - CENTRIFUGO_JWT_SECRET_FILE=/run/secrets/backend_centrifugo_jwt_secret
      - SENTRY_DSN_FILE=/run/secrets/backend_sentry_dsn
      - STRIPE_SECRET_KEY_FILE=/run/secrets/backend_stripe_secret_key
      - STRIPE_WEBHOOK_SECRET_FILE=/run/secrets/backend_stripe_webhook_secret
      - OPENROUTER_API_KEY_FILE=/run/secrets/backend_openrouter_api_key
      - GOOGLE_OAUTH_CLIENT_ID_FILE=/run/secrets/backend_google_oauth_client_id
      - GOOGLE_OAUTH_CLIENT_SECRET_FILE=/run/secrets/backend_google_oauth_client_secret

    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
      rollback_config:
        parallelism: 1
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.floww-backend-api.rule=Host(`app.usefloww.dev`) && (PathPrefix(`/api`) || PathPrefix(`/auth`) || PathPrefix(`/v2`) || PathPrefix(`/admin`) || PathPrefix(`/webhook`) || PathPrefix(`/oauth`))"
        - "traefik.http.routers.floww-backend-api.entrypoints=websecure"
        - "traefik.http.routers.floww-backend-api.tls.certresolver=myresolver"
        - "traefik.http.routers.floww-backend-api.service=floww-backend"
        - "traefik.http.services.floww-backend.loadbalancer.server.port=8000"

    healthcheck:
      test: ["CMD-SHELL", "python -c 'import requests; import sys; sys.exit(0) if requests.get(\"http://localhost:8000/api/health\").ok else sys.exit(1)'"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

secrets:
  backend_auth_client_secret:
    external: true
  backend_encryption_key:
    external: true
  backend_aws_access_key_id:
    external: true
  backend_aws_secret_access_key:
    external: true
  backend_database_password:
    external: true
  backend_session_secret_key:
    external: true
  backend_workflow_jwt_secret:
    external: true
  backend_centrifugo_api_key:
    external: true
  backend_centrifugo_jwt_secret:
    external: true
  backend_sentry_dsn:
    external: true
  backend_stripe_secret_key:
    external: true
    name: backend_stripe_secret_key_v2
  backend_stripe_webhook_secret:
    external: true
    name: backend_stripe_webhook_secret_v2
  backend_openrouter_api_key:
    external: true
  backend_google_oauth_client_id:
    external: true
  backend_google_oauth_client_secret:
    external: true

networks:
  traefik-net:
    external: true
