version: "3.8"

services:
  centrifugo:
    image: "ghcr.io/usefloww/floww-centrifugo:latest"

    networks:
      - traefik-staging-net

    secrets:
      - staging_backend_centrifugo_api_key

    environment:
      - CENTRIFUGO_API_KEY_FILE=/run/secrets/staging_backend_centrifugo_api_key
      - CENTRIFUGO_ADMIN_ENABLED=true
      - CENTRIFUGO_ADMIN_INSECURE=true
      - CENTRIFUGO_CONNECT_PROXY_ENDPOINT=http://floww-backend-staging_app:8000/centrifugo/connect
      - CENTRIFUGO_SUBSCRIBE_PROXY_ENDPOINT=http://floww-backend-staging_app:8000/centrifugo/subscribe
      - CENTRIFUGO_ALLOWED_ORIGINS=["https://app.flow.toondn.app"]
      - CENTRIFUGO_ALLOW_ANONYMOUS=true

    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
      rollback_config:
        parallelism: 1
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.centrifugo-staging.rule=Host(`app.flow.toondn.app`) && PathPrefix(`/ws`)"
        - "traefik.http.routers.centrifugo-staging.entrypoints=websecure"
        - "traefik.http.routers.centrifugo-staging.tls.certresolver=myresolver"
        - "traefik.http.services.centrifugo-staging-service.loadbalancer.server.port=8000"

    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  app:
    image: "ghcr.io/usefloww/floww-backend:latest"

    networks:
      - traefik-staging-net

    secrets:
      - staging_backend_auth_client_secret
      - staging_backend_encryption_key
      - staging_backend_aws_access_key_id
      - staging_backend_aws_secret_access_key
      - staging_backend_database_password
      - staging_backend_session_secret_key
      - staging_backend_workflow_jwt_secret
      - staging_backend_centrifugo_api_key
      - staging_backend_centrifugo_jwt_secret
      - backend_sentry_dsn
      - staging_backend_stripe_secret_key
      - staging_backend_stripe_webhook_secret
      - staging_backend_openrouter_api_key

    environment:
      # Non-sensitive configuration
      - AUTH_CLIENT_ID=client_01K6QQP8Q721ZX1YM1PBV3EWMR
      - AUTH_ISSUER_URL=https://great-gradient-36-staging.authkit.app
      - AWS_REGION=us-east-1
      - RUNTIME_TYPE=lambda
      - DATABASE_USER=postgres
      - DATABASE_HOST=floww.cklmackcedxs.us-east-1.rds.amazonaws.com
      - DATABASE_PORT=5432
      - DATABASE_NAME=postgres_staging
      - CENTRIFUGO_HOST=centrifugo-staging_centrifugo
      - CENTRIFUGO_PORT=8000
      - CENTRIFUGO_PUBLIC_URL=https://app.flow.toondn.app
      - PUBLIC_API_URL=https://app.flow.toondn.app
      - SENTRY_ENVIRONMENT=staging
      - REGISTRY_URL=501046919403.dkr.ecr.us-east-1.amazonaws.com
      - REGISTRY_REPOSITORY_NAME=trigger-lambda
      - IS_CLOUD=true
      - STRIPE_PUBLISHABLE_KEY=pk_test_51SToIL6Sf2jh0J7U2zK8kB10riNkBMYt0l29srRSjhDcH0fVq1wkvJsz5NVrrHAKJuikDg5ZmOeAKFv2AkghqR0h006yNZRHDx
      - STRIPE_PRICE_ID_PRO=price_1SToiy6Sf2jh0J7UlFDKRxbJ

      # Secret file paths (read by updated settings.py)
      - AUTH_CLIENT_SECRET_FILE=/run/secrets/staging_backend_auth_client_secret
      - ENCRYPTION_KEY_FILE=/run/secrets/staging_backend_encryption_key
      - AWS_ACCESS_KEY_ID_FILE=/run/secrets/staging_backend_aws_access_key_id
      - AWS_SECRET_ACCESS_KEY_FILE=/run/secrets/staging_backend_aws_secret_access_key
      - DATABASE_PASSWORD_FILE=/run/secrets/staging_backend_database_password
      - SESSION_SECRET_KEY_FILE=/run/secrets/staging_backend_session_secret_key
      - WORKFLOW_JWT_SECRET_FILE=/run/secrets/staging_backend_workflow_jwt_secret
      - CENTRIFUGO_API_KEY_FILE=/run/secrets/staging_backend_centrifugo_api_key
      - CENTRIFUGO_JWT_SECRET_FILE=/run/secrets/staging_backend_centrifugo_jwt_secret
      - SENTRY_DSN_FILE=/run/secrets/backend_sentry_dsn
      - STRIPE_SECRET_KEY_FILE=/run/secrets/staging_backend_stripe_secret_key
      - STRIPE_WEBHOOK_SECRET_FILE=/run/secrets/staging_backend_stripe_webhook_secret
      - OPENROUTER_API_KEY_FILE=/run/secrets/staging_backend_openrouter_api_key

    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
      rollback_config:
        parallelism: 1
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.floww-backend-staging-api.rule=Host(`app.flow.toondn.app`) && (PathPrefix(`/api`) || PathPrefix(`/auth`) || PathPrefix(`/v2`) || PathPrefix(`/admin`))"
        - "traefik.http.routers.floww-backend-staging-api.entrypoints=websecure"
        - "traefik.http.routers.floww-backend-staging-api.tls.certresolver=myresolver"
        - "traefik.http.routers.floww-backend-staging-api.service=floww-backend-staging"
        - "traefik.http.services.floww-backend-staging.loadbalancer.server.port=8000"

    healthcheck:
      test: ["CMD-SHELL", "python -c 'import requests; import sys; sys.exit(0) if requests.get(\"http://localhost:8000/api/health\").ok else sys.exit(1)'"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

secrets:
  staging_backend_auth_client_secret:
    external: true
  staging_backend_encryption_key:
    external: true
  staging_backend_aws_access_key_id:
    external: true
  staging_backend_aws_secret_access_key:
    external: true
  staging_backend_database_password:
    external: true
  staging_backend_session_secret_key:
    external: true
  staging_backend_workflow_jwt_secret:
    external: true
  staging_backend_centrifugo_api_key:
    external: true
  staging_backend_centrifugo_jwt_secret:
    external: true
  backend_sentry_dsn:
    external: true
  staging_backend_stripe_secret_key:
    external: true
  staging_backend_stripe_webhook_secret:
    external: true
  staging_backend_openrouter_api_key:
    external: true

networks:
  traefik-staging-net:
    external: true
